### ISSUE TITLE
Does not highlight tuples inside bracket expressions

### ISSUE THREAD

**Issue by beef331** [alaviss/tree-sitter-nim#25]
```nim
var a: seq[(int, int)]
```
Results in 
![image](https://github.com/alaviss/tree-sitter-nim/assets/11792483/3f6044b9-da47-4d6e-9338-25f94a7abc7c)

Whereas
```nim
var a: seq[int, int]
```
Results in
![image](https://github.com/alaviss/tree-sitter-nim/assets/11792483/a1efa20b-e52d-4850-abcc-06c72f6e0abb)

**Comment by alaviss** [comment]
This is now out of scope for this project. Highlight queries will be handled by downstream consumers like nvim-treesitter.
