### ISSUE TITLE
parser bug `var x:* type`

### ISSUE THREAD

**Issue by aMOPel** [alaviss/tree-sitter-nim#35]
### Current Behaviour

`var x:* type` 

is falsely parsed as

```scheme
assignment
  left: var_type
    type_expression
      infix_expression
        left: identifier
        operator: operator
        right: identifier
```

### Expected Behaviour

```scheme
var_section
  variable_declaration
    symbol_declaration_list
      symbol_declaration
        name: exported_symbol
          identifier
    type: type_expression
      identifier
```

Section from the docs:

> `.`, `=`, `:`, `::` are not available as general operators; they are used for other notational purposes.
`*:` is as a special case treated as the two tokens `*` and `:` (to support `var v*: T`).

https://nim-lang.org/docs/manual.html#lexical-analysis-operators

**Comment by alaviss** [comment]
I believe you meant `*:` :stuck_out_tongue: 

Fix is on the way.
