### ISSUE TITLE
Trailing comma in `(generic_parameter_list)` gives ERROR

### ISSUE THREAD

**Issue by aMOPel** [alaviss/tree-sitter-nim#38]
### Current Behavior

```nim
proc a[T,]() = discard
```

```scheme
(source_file [1, 0] - [2, 0]
  (proc_declaration [1, 0] - [1, 22]
    name: (identifier [1, 5] - [1, 6])
    generic_parameters: (generic_parameter_list [1, 6] - [1, 10]
      (parameter_declaration [1, 7] - [1, 8]
        (symbol_declaration_list [1, 7] - [1, 8]
          (symbol_declaration [1, 7] - [1, 8]
            name: (identifier [1, 7] - [1, 8]))))
      (ERROR [1, 8] - [1, 9]))
    parameters: (parameter_declaration_list [1, 10] - [1, 12])
    body: (statement_list [1, 15] - [1, 22]
      (discard_statement [1, 15] - [1, 22]))))
```

### Expected Behavior

Trailing commas should be allowed for generic parameters.

### Notes

It's weird, since trailing commas in `(parameter_declaration_list)` parse fine and they use the same rule.

**Comment by alaviss** [comment]
> It's weird, since trailing commas in `(parameter_declaration_list)` parse fine and they use the same rule.

It's happening at the `symbol_declaration_list`, which doesn't tolerate trailing commas.

I just tested with Nim and this is valid code:

```nim
type A[T,: int] = int
```

So a fix is coming soon.
