### ISSUE TITLE
Bring scanner.cc down to C++03

### ISSUE THREAD

**Issue by aMOPel** [alaviss/tree-sitter-nim#43]
https://github.com/nvim-treesitter/nvim-treesitter/pull/5437#issuecomment-1732526918

Merge into nvim-treesitter is blocked due to this.

**Comment by alaviss** [comment]
No one should be using C++ older than C++11. Compilers have supported that since forever.

**Comment by aMOPel** [comment]
Just thought about it:

If you're ever gonna start another rewrite, maybe
you could write the scanner in Nim and compile to pure C and be compatible with everything. Plus Nim is just nicer than Cpp.

**Comment by alaviss** [comment]
That's actually the original plan, but Nim's generated C is platform-specific.

**Comment by aMOPel** [comment]
Oh. That is a bummer, I didn't know that.

But you could provide a makefile in the repo that takes care of the platform specific aspect, ie generates the appropriate platform specific scanner.c. Because nvim-treesitter would actually prefer it, if there was a makefile in the parser repo.

Or does that not work?

**Comment by alaviss** [comment]
I could, but their maintainer make a strong stance about how they don't really want to support scanners that use C++ newer than the 2003 revision.

I doubt they would take this parser even if I wrote the `Makefile`.

**Comment by aMOPel** [comment]
Yeah they don't actually support makefiles in parser repos. I misunderstood that.

**Comment by aMOPel** [comment]
> but Nim's generated C is platform-specific

It is possible with `--os:any`

https://nim-lang.org/docs/nimc.html#nim-for-embedded-systems

I asked on the discord and they also recommended this article

https://mike.fo/blog/nim-is-actually-portable

**Comment by alaviss** [comment]
> It is possible with `--os:any`
> 
> https://nim-lang.org/docs/nimc.html#nim-for-embedded-systems

You can avoid OS-specific stuff this way but you can't avoid architecture-specific stuff

> I asked on the discord and they also recommended this article
> 
> https://mike.fo/blog/nim-is-actually-portable

It's an application thing and doesn't apply well to the library use case, esp when you want to load it into an application.

Btw, I'm available on both Discord and Matrix as leorize, if you prefer to talk there :)

**Comment by aMOPel** [comment]
wrote to leorize2
