### ISSUE TITLE
AST breaks with `(` in declaration section

### ISSUE THREAD

**Issue by aMOPel** [alaviss/tree-sitter-nim#64]
```nim
let 
  a: int = 
```

```nim
let_section [93, 0] - [94, 10]
  "let" [93, 0] - [93, 3]
  variable_declaration [94, 2] - [94, 8]
    symbol_declaration_list [94, 2] - [94, 3]
      symbol_declaration [94, 2] - [94, 3]
        name: identifier [94, 2] - [94, 3]
    type: ":" [94, 3] - [94, 4]
    type: type_expression [94, 5] - [94, 8]
      identifier [94, 5] - [94, 8]
  ERROR [94, 9] - [94, 10]
    "=" [94, 9] - [94, 10]
```

when typing `(` it breaks the `(let_section)`

```nim
let 
  a: int = (
```

```nim
"let" [93, 0] - [93, 3]
symbol_declaration_list [94, 2] - [94, 3]
  symbol_declaration [94, 2] - [94, 3]
    name: identifier [94, 2] - [94, 3]
":" [94, 3] - [94, 4]
type_expression [94, 5] - [94, 8]
  identifier [94, 5] - [94, 8]
"=" [94, 9] - [94, 10]
"(" [94, 11] - [94, 12]
```

**Comment by alaviss** [comment]
I have a fix for this by restructuring how statements might end, but the parser size grew over 100MiB, which is over GitHub's limit.

I think we will have to consider working with downstream users about downloading parser via GitHub Releases or similar mechanism. It is clear that parsing Nim correctly requires a very big parser.

**Comment by aMOPel** [comment]
That would mean rolling out your own download tool an not using the service of nvim-treesitter.

Plus, moving our queries out of nvim-treesitter would greatly reduce discoverability.

**Comment by alaviss** [comment]
Given that tree-sitter 1.0 have "not shipping parser.c within repo" as a [goal](https://github.com/tree-sitter/tree-sitter/issues/930), I think sooner or later all downstreams will have to move.

I'd prefer to have nvim-treesitter carry the parser still, so going that path does require their cooperation.

Git LFS still requires the user to have Git-LFS installed, and not to mention that there is a GitHub-enforced quota for using them, where usage in fork also counts against the main repo...

I'll still work on trying to optimize the parser size to avoid needing a custom download pipeline, but this is not easy.
