### ISSUE TITLE
parsing breaks in `system.nim` from line 186

### ISSUE THREAD

**Issue by doongjohn** [alaviss/tree-sitter-nim#66]
![image](https://github.com/alaviss/tree-sitter-nim/assets/40219740/fbf03b1e-2b03-4cfb-941e-8d30df39bf16)
also there are quite a lot of ERROR nodes in `system.nim`

**Comment by alaviss** [comment]
The grammar doesn't handle a type declaration without body at the moment but should be simple to fix.

It might have implications for error handling, though
