### ISSUE TITLE
empty doc comment makes problems with injection

### ISSUE THREAD

**Issue by aMOPel** [alaviss/tree-sitter-nim#68]
I just noticed a big oddity with empty doc comments:

Consider:
```nim
let x = call[link_text](link_dest)
```

```scm
let_section [0, 0] - [0, 34]
  variable_declaration [0, 4] - [0, 34]
    symbol_declaration_list [0, 4] - [0, 5]
      symbol_declaration [0, 4] - [0, 5]
        name: identifier [0, 4] - [0, 5]
    value: call [0, 8] - [0, 34]
      function: bracket_expression [0, 8] - [0, 23]
        left: identifier [0, 8] - [0, 12]
        right: argument_list [0, 13] - [0, 22]
          identifier [0, 13] - [0, 22]
      argument_list [0, 23] - [0, 34]
        identifier [0, 24] - [0, 33]
```

Now add an empty doc comment:
```nim
let x = call[link_text](link_dest)
##
```

```scm
let_section [0, 0] - [0, 34]
  variable_declaration [0, 4] - [0, 34]
    symbol_declaration_list [0, 4] - [0, 5]
      symbol_declaration [0, 4] - [0, 5]
        name: identifier [0, 4] - [0, 5]
    value: call [0, 8] - [0, 34]
      function: bracket_expression [0, 8] - [0, 23]
        left: identifier [0, 8] - [0, 12]
        right: argument_list [0, 13] - [0, 22]
          identifier [0, 13] - [0, 22]
      argument_list [0, 23] - [0, 34]
        identifier [0, 24] - [0, 33]
documentation_comment [1, 0] - [1, 2]   
  comment_content [1, 2] - [1, 2]
inline_link [0, 12] - [0, 34]                  <- markdown injected on the whole file
  link_text [0, 13] - [0, 22]
  link_destination [0, 24] - [0, 33]
```

For some reason, if there is an empty doc comment (nothing after `##` not even a space), anywhere in the file, the markdown that should be injected in the `(comment_content)`, get's injected at the root of the AST and will override all highlighting. Pretty nasty.

Not sure if it's a nvim treesitter injection bug or a parser issue.

**Comment by aMOPel** [comment]
same goes for an empty multiline doc comment `##[]##`.

**Comment by aMOPel** [comment]
It seems like it's part of the nvim injection logics fault. It can't handle the edge case of injecting something into a range of length 0.

Or what do you think?

It should be possible to circumvent this issue on our side, if you don't add the (comment_content) node when it's completely empty.

Luckily this cannot happen with all the string injections, since those don't add a (string_content) node in that case.

**Comment by aMOPel** [comment]
Apparently this bug is fixed in nvim > 0.9.1

**Comment by alaviss** [comment]
If that's the case then there's nothing to do on our side.

**Comment by aMOPel** [comment]
Honestly I don't think it a bad idea to fix it anyway, since I believe many people don't update their nvim regularly, eg consider people staying on older LTS versions of distros who install nvim over package manager.

Or is it that involved to not add the (comment_content) when it is empty?

**Comment by alaviss** [comment]
> Or is it that involved to not add the (comment_content) when it is empty?

While this can be done for documentation comment, this is impossible for single-line comments as they must have an unambiguous termination sequence (ie. `seq(x, optional(y))` is not allowed since it is ambiguous whether the comment will have `y`).

We might have to consider removing `comment_content` for single-line comments.
