### ISSUE TITLE
Please add build information

### ISSUE THREAD

**Issue by niontrix** [alaviss/tree-sitter-nim#81]
Hi there,

first of all thanks for working of the tree-sitter grammar for Nim!
Could you please show me how to compile this project and get a useable nim.so?
I did do a `cargo build` in the project directory which seems to have compiled just fine, but I don't know what to do with the artifacts created in the target directory.
Could you also please add the build information to the project readme ,so other people like me, that are unfamiliar with the rust ecosystem, can build the tree-sitter-nim grammar?
Thanks in advance!

KR

**Comment by alaviss** [comment]
Similar to many tree-sitter grammars, this project does not come with a build system.

The cargo file there is only used to build a glue library for Rust and not for the grammar.

To build the library, you just have to call the C compiler like this:

```
$ cc -O2 -shared -Isrc -fPIC -o nim.so src/parser.c src/scanner.c
```

**Comment by niontrix** [comment]
It worked! Thanks for the explanation!
